version: '2.4'

x-es:
  &es
  image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3-amd64
  ulimits:
    memlock:
      soft: -1
      hard: -1
  networks:
    - esnet
  volumes:
    - esdata:/usr/share/elasticsearch/data

services:
  flathub-es:
    << : *es
    container_name: flathub-es
    environment:
      # backward compatibility for cluster name:
      - cluster.name=astrosums
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - "discovery.seed_hosts=flathub-es"
      - "cluster.initial_master_nodes=flathub-es"
      - "node.max_local_storage_nodes=8"
      - "node.name=flathub-es"
      - "xpack.security.enabled=false"
    expose:
      - "9200"
    ports:
      - "127.0.0.1:9200:9200"
  es:
    << : *es
    environment:
      - cluster.name=flathub
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - "discovery.seed_hosts=flathub-es"
      - "cluster.initial_master_nodes=flathub-es"
      - "node.max_local_storage_nodes=8"
      - "xpack.security.enabled=false"
    scale: 4
  flathub:
    build: .
    image: flatironinstitute/flathub
    networks:
      - esnet
    ports:
      - "80:8092"
    depends_on:
      - flathub-es

volumes:
  esdata:

networks:
  esnet:
