apiVersion: apps/v1
kind: Deployment
metadata:
  name: flathub
spec:
  replicas: 2
  selector:
    matchLabels:
      name: flathub
  template:
    metadata:
      labels:
        name: flathub
    spec:
      containers:
      - image: flatironinstitute/flathub:latest
        name: flathub
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 4
            memory: 16Gi
        ports:
        - containerPort: 8092
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
            httpHeaders:
              - name: accept
                value: application/json
          initialDelaySeconds: 30
          timeoutSeconds: 15
          periodSeconds: 60
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: flathub
spec:
  selector:
    name: flathub
  ports:
  - name: http
    port: 80
    targetPort: http
  #externalIPs:
