resolver: lts-19.33
packages:
- '.'
extra-deps:
  - web-inv-route-0.1.3.2
  - git: https://github.com/dylex/waimwork
    commit: 8ccaa63ac6b80a4ebc9ad7d61ca38cbb009e8f3c
  - git: https://github.com/dylex/hs-hdf5
    commit: b0b56b5f5b69663ed70bc29055ba9971f177eb9b
  - git: https://github.com/ondrap/json-stream
    commit: e51d810c8b8bf312da9cb8b81cfd83d0feecc3fa
flags:
  web-inv-route:
    snap: false
    happstack: false
  aeson:
    cffi: true
    #fast: false
