resolver: lts-20.26
packages:
- '.'
extra-deps:
  - bzlib-0.5.1.0
  - web-inv-route-0.1.3.2
  - invertible-0.2.0.8
  - git: https://github.com/dylex/waimwork
    commit: 8ccaa63ac6b80a4ebc9ad7d61ca38cbb009e8f3c
  - git: https://github.com/dylex/hs-hdf5
    commit: fef08a26f3c8add943beb8463ef7a0cc41245df5
  - git: https://github.com/ondrap/json-stream
    commit: e51d810c8b8bf312da9cb8b81cfd83d0feecc3fa
flags:
  web-inv-route:
    snap: false
    happstack: false
  aeson:
    cffi: true
